language: ruby
rvm:
- 2.4.1
addons:
  code_climate:
    repo_token: "$CODECLIMATE_REPO_TOKEN"
install:
- travis_retry bundle install
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter
deploy:
  provider: rubygems
  api_key:
    secure: lEUHxqrw71LBPWKy8PS9EriAFwbeNDsopIkEX1ssU2FbZSMCiE4p4AYC+C+KjmoJ7mNjz+0jtqEIfVgKT93CpP6AqRGG3uxHBXhslyuEFe/ej+QrMb+gzIDZIA3leW0IgPhi7Rtk24RssPmtFAs0wAMM3iOS8lOPpqO5kWGmWMExezcpiVxPld2KIZksLUvwflyOs9aG1+n0Zt5FNyrXKI3W9rK3BytwnPZn2f4ahc8IP5u5jjhnM0tvG697SNQm/GKGkOcQ3iJgZ7RpakosHvocrTGUH+q1FZBpqG2FDKn0HygpQCs30puEIqAlnCBxDoI53G/xjP6CaNr7JCLBYjUMJZ91nJvwHaMfA3nnDEEI3p+MrsV3lwAyvpXQxJeWt3hM1bHcH2pIql2hGMlx6f5XnPCvFaUQwN1Fi534xVCBOSEXCr2G9oStOpW5SA/U7jvohUiCZhIK7eSR5i4w1EbCsU9nQWZYjvX0EprYoVlBqgLGZEKK02JCIwGXPLVYfJwzNBv0uBtiNBkwO8jHVaAEVrJL4Ka8TBy/V3B86mZ+W5EvP6kn6lJCh8Sh7bwpj0NXKllRw2sSz9ukybayLan/OcSgj98LgRKJ09iydxwsTFIVD4kzuGidF+qtT6ImLgD4qWMr4mgCSlsJp83fOzpdzDVLlz+T3tSVB42tNjE=
  gem: omniauth-globus
  on:
    tags: true
    repo: datacite/omniauth-globus
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
